### Step 1a: Create an account. Should return the account ID and HTTP 201 status
POST http://54.234.192.121:8080/accounts/
Content-Type: application/json

{
  "name": "Saurabh Agarwal",
  "email": "saurabh.agarwal@udaan.com",
  "phone": "123-234-345",
  "company": "Udaan"
}

### Step 1b: Create another account. Should return the account ID and HTTP 201 status as well
POST http://54.234.192.121:8080/accounts/
Content-Type: application/json

{
  "name": "Requester Kumar",
  "email": "requester.kumar@test.com",
  "phone": "888-888-888",
  "company": "Test"
}

### Step 2a: Create an availability on first account. Should return the availability ID and HTTP 201 status
POST http://54.234.192.121:8080/accounts/1/availability/
Content-Type: application/json

{
  "dayOfWeek": "MONDAY",
  "startTime": "12:00",
  "endTime": "17:00"
}

### Step 2b: Create an availability on second account. Should return the availability ID and HTTP 201 status
POST http://54.234.192.121:8080/accounts/2/availability/
Content-Type: application/json

{
  "dayOfWeek": "MONDAY",
  "startTime": "13:00",
  "endTime": "14:00"
}

### Step 3: Create a meeting link with first account as the host. Should return the meeting link ID and HTTP 201 status
POST http://54.234.192.121:8080/accounts/1/meeting-links/
Content-Type: application/json

{
  "durationInMins": 30,
  "dates": ["2023-01-30"]
}

### Step 4: Find overlap in availabilities between first and second accounts. Should return the overlap window and HTTP 200 status
GET http://54.234.192.121:8080/accounts/1/overlap/2

### Step 5: Request a meeting from second account to first account using the meeting link above. Should return the meeting ID and HTTP 201 status
POST http://54.234.192.121:8080/accounts/1/meeting-links/1/meetings/
Content-Type: application/json

{
  "date": "2023-01-30",
  "startTime": "13:30",
  "endTime": "14:00",
  "requesterAccountId": 2
}

### Step 6a: Check first account's availabilities. Should the remaining availability and HTTP 200 status
GET http://54.234.192.121:8080/accounts/1/availability

### Step 6b: Check second account's availabilities. Should the remaining availability and HTTP 200 status
GET http://54.234.192.121:8080/accounts/2/availability
